version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: new
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      MYSQL_DATABASE: new-employee-training
      MYSQL_USER: new-employee-training
      MYSQL_PASSWORD: new-employee-training
      MYSQL_ROOT_PASSWORD: new-employee-training
      TZ: Asia/Tokyo
    volumes: 
      - .docker/mysql:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d
    ports:
      - 23306:3306